services:
  auth:
    build:
      context: ./src/services
      dockerfile: ./Auth/Dockerfile

  service:
    build:
      context: ./src/services
      dockerfile: ./Main/Dockerfile

  activity:
    build:
      context: ./src/services
      dockerfile: ./Activity/Dockerfile

  web:
    build:
      context: ./src/clients/web
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_SERVICE_BASE_URL=${VITE_AUTH_SERVICE_BASE_URL}
        - VITE_MAIN_SERVICE_BASE_URL=${VITE_MAIN_SERVICE_BASE_URL}
        - VITE_ACTIVITY_SERVICE_BASE_URL=${VITE_ACTIVITY_SERVICE_BASE_URL}
    image: karemsfar/mmgmt-web:latest
