services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mmgmt
    volumes:
      - postgres_data:/var/lib/postgresql
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  otel-lgtm:
    container_name: otel-lgtm-mmgmt
    image: grafana/otel-lgtm:latest
    environment:
      - GF_SECURITY_ADMIN_USER=todokarem
      - GF_SECURITY_ADMIN_PASSWORD=todokarem
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/observability/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    # ports:
    #   - "3000:3000"
    #   - "4317"
    #   - "4318"

  auth:
    image: karemsfar/mmgmt-auth:latest
    environment:
      - Database__DatabaseType=${Auth_Database__DatabaseType}
      - Database__ConnectionString=${Auth_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}
      - googleclient_id=${googleclient_id}
      - googleclient_secret=${googleclient_secret}
      - OTEL__ENDPOINT=${OTEL__ENDPOINT}
    depends_on:
      - db
      - otel-lgtm

  service:
    image: karemsfar/mmgmt-service:latest
    environment:
      - Database__DatabaseType=${Main_Database__DatabaseType}
      - Database__ConnectionString=${Main_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}
      - OTEL__ENDPOINT=${OTEL__ENDPOINT}
      - RabbitMq__Host=rabbitmq
      - RabbitMq__UserName=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASS}
    depends_on:
      db:
        condition: service_started
      otel-lgtm:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  activity:
    image: karemsfar/mmgmt-activity:latest
    environment:
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}    
      - RabbitMq__Host=rabbitmq
      - RabbitMq__UserName=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASS}
      - Redis__Configuration=${REDIS__CONFIGURATION}
      - OTEL__ENDPOINT=${OTEL__ENDPOINT}
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  web:
    image: karemsfar/mmgmt-web:latest

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - service
      - web
      - otel-lgtm

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    # ports:
    #   - "5672:5672" # AMQP
    #   - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: always

volumes:
  postgres_data:
  redis_data:
