services:
  auth:
    build:
      context: ./src/services
      dockerfile: ./Auth/Dockerfile
    image: karemsfar/mmgmt-auth:latest
    ports:
      - 81:81
    environment:
      - Database__DatabaseType=${Auth_Database__DatabaseType}
      - Database__ConnectionString=${Auth_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}

  service:
    build:
      context: ./src/services
      dockerfile: ./Main/Dockerfile
    image: karemsfar/mmgmt-service:latest
    ports:
      - 82:81
    environment:
      - Database__DatabaseType=${Main_Database__DatabaseType}
      - Database__ConnectionString=${Main_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}

  web:
    build:
      context: ./src/clients/web
      dockerfile: Dockerfile.local
      args:
        - REACT_APP_AUTH_SERVICE_BASE_URL=${REACT_APP_AUTH_SERVICE_BASE_URL}
        - REACT_APP_MAIN_SERVICE_BASE_URL=${REACT_APP_MAIN_SERVICE_BASE_URL}
    volumes:
      -  ./src/clients/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # map the React development server
      - "9229:9229"  # optional: map Node.js debugger port
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
