services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mmgmt
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    build:
      context: ./src/services
      dockerfile: ./Auth/Dockerfile
    image: karemsfar/mmgmt-auth:latest
    environment:
      - Database__DatabaseType=${Auth_Database__DatabaseType}
      - Database__ConnectionString=${Auth_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}

  service:
    build:
      context: ./src/services
      dockerfile: ./Main/Dockerfile
    image: karemsfar/mmgmt-service:latest
    environment:
      - Database__DatabaseType=${Main_Database__DatabaseType}
      - Database__ConnectionString=${Main_Database__ConnectionString}
      - Jwt__JwtAccessKey=${Jwt__JwtAccessKey}
      - Jwt__JwtRefreshKey=${Jwt__JwtRefreshKey}

  web:
    build:
      context: ./src/clients/web
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_SERVICE_BASE_URL=${VITE_AUTH_SERVICE_BASE_URL}
        - VITE_MAIN_SERVICE_BASE_URL=${VITE_MAIN_SERVICE_BASE_URL}
    image: karemsfar/mmgmt-web:latest
   
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - service
      - web

volumes:
  postgres_data: